# Generated by Django 5.1.3 on 2024-11-08 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_user_is_admin_user_is_parent_user_is_student_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_parent",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_student",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_teacher",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Teacher", "Teacher"),
                    ("Student", "Student"),
                    ("Parent", "Parent"),
                ],
                default="Student",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="parent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
