# Generated by Django 5.1.3 on 2024-11-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_alter_student_user_alter_teacher_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(default="unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="teacher",
            name="name",
            field=models.CharField(default="unknown", max_length=100),
        ),
    ]
