# Generated by Django 5.1.3 on 2024-11-13 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0006_remove_examination_subject_attendance_classes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="classes",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.class",
            ),
        ),
    ]
